export const userConstants = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',

	RESENDEMAIL_REQUEST: 'USERS_RESENDEMAIL_REQUEST',
	RESENDEMAIL_SUCCESS: 'USERS_RESENDEMAIL_SUCCESS',
	ADDUSERSOCKET: 'USERS_ADDUSERSOCKET',

	RESETPASSEMAIL_REQUEST: 'USERS_RESETPASSEMAIL_REQUEST',
	RESETPASSEMAIL_SUCCESS: 'USERS_RESETPASSEMAIL_SUCCESS',
	RESETPASS_REQUEST: 'USERS_RESETPASS_REQUEST',
	RESETPASS_SUCCESS: 'USERS_RESETPASS_SUCCESS',

	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',

	LOGOUT: 'USERS_LOGOUT',

	GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
	GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',

	GETPROFILE_REQUEST: 'USERS_GETPROFILE_REQUEST',
	GETPROFILE_SUCCESS: 'USERS_GETPROFILE_SUCCESS',

	GETMATCH_REQUEST: 'USERS_GETMATCH_REQUEST',
	GETMATCH_SUCCESS: 'USERS_GETMATCH_SUCCESS',

	GETVISITS_REQUEST: 'USERS_GETVISITS_REQUEST',
	GETVISITS_SUCCESS: 'USERS_GETVISITS_SUCCESS',

	LIKE_REQUEST: 'USERS_LIKE_REQUEST',
	LIKE_SUCCESS: 'USERS_LIKE_SUCCESS',
	LIKEMATCH_SUCCESS: 'USERS_LIKEMATCH_SUCCESS',

	BLOCK_REQUEST: 'USERS_BLOCK_REQUEST',
	BLOCK_SUCCESS: 'USERS_BLOCK_SUCCESS',
	
	REPORT_REQUEST: 'USERS_REPORT_REQUEST',
	REPORT_SUCCESS: 'USERS_REPORT_SUCCESS',
	
	// DELETE_REQUEST: 'USERS_DELETE_REQUEST',
	// DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
	// DELETE_FAILURE: 'USERS_DELETE_FAILURE',
	
	UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
	UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
	
	UPDATEPHOTO_SUCCESS: 'USER_UPDATEPHOTO_SUCCESS',
	UPDATEPHOTO_REQUEST: 'USER_UPDATEPHOTO_REQUEST',
	
	DELETEPHOTO_SUCCESS: 'USER_DELETEPHOTO_SUCCESS',
	DELETEPHOTO_REQUEST: 'USER_DELETEPHOTO_REQUEST',
	
	//SOCKET
	INIT_ROOMS_SUCCESS: 'USER_INIT_ROOMS_SUCCESS',
	
	ADD_MESSAGE_SUCCESS: 'USER_ADD_MESSAGE_SUCCESS',
	
	INIT_NOTIF_SUCCESS: 'USER_INIT_NOTIF_SUCCESS',
	ADD_NOTIF_SUCCESS: 'USER_ADD_NOTIF_SUCCESS',
	READ_NOTIF_SUCCESS: 'USER_READ_NOTIF_SUCCESS',
	UPDATE_USERSCONNECTED_SUCCESS: 'USER_UPDATE_USERSCONNECTED_SUCCESS'
};